### ISSUE TITLE
Consider using a Localisation plugin without Context

### ISSUE THREAD

**Issue by Alqueraf** [levin-riegner/flutter-template#1]
Currently, l10n requires access to the BuildContext in order to offer localized Strings.

Investigate other alternatives that allow accessing Strings without a BuildContext.

- [ ] What 3rd party service can we use to export/import translation files if we use https://pub.dev/packages/easy_localization?
- [ ] Can l10n be used without Context?

**Comment by JTorrus** [comment]
Found out `l10n` can also be accessed without `BuildContext`.  Check this example.

```dart
    // Use ".current" when you don't have/access to the context.
    S l10n() => S.current;

    Scaffold(
      appBar: AppBar(
        title: Text(super.l10n().pickYourColor),
      ),
      body: Container(),
    );

    // Use this when you have access to context in your class/method.
    S.of(context).welcome("Julia Child");
```
